services:
  backend:
    build: ./backend             
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:academy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_ENABLED: "true"
      SERVER_PORT: 8091

  frontend:
    build: ./frontend            
    ports:
      - "3000:3000"
    depends_on:
      - backend
